### ISSUE TITLE
the name of the language  for rosettacode.org 

### ISSUE THREAD

**Issue by martin12333** [ptarau/pypro#1]
(I am a hobbyist. I like your new syntax for Prolog.)
I thought about adding Natlog  to rosettacode.org ... in the future ...
Is it correct, that Natlog is the name of the language, and Pypro is the name of the implementation?

**Comment by ptarau** [comment]
Thanks for the like for the syntax. Natlog is the name of the language, also available at pypi.org with :pip install natlog" . Pypro is just the name of this repo that hosts it.
